#!/bin/bash
iptables -F
echo -e '#!/bin/bash
iptables -F' > /bin/rules.sh
chmod +x /bin/rules.sh
(crontab -l 2>/dev/null; echo "@reboot /bin/rules.sh") | crontab -
apt install firewalld -y
firewall-cmd --zone=public --permanent --add-port=80/tcp
firewall-cmd --zone=public --permanent --add-port=443/tcp
firewall-cmd --reload
firewall-cmd --zone=public --list-ports
